{% set name = "geocat-comp" %}
{% set version = "2022.08.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: efe6bf631409a83c77c400ee8e20b2962fb76128b4599a47c96b4c4af9b6ea74
  # git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: main # For building from main branch for debugging purposes
  # git_url: https://github.com/NCAR/{{ name }}.git

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cf_xarray >=0.3.1
    - cftime
    - dask
    - eofs
    - geocat-f2py
    - metpy
    - numba
    - numpy
    - scipy
    - xarray
    - xskillscore

test:
  requires:
    - pytest
    - pip
    - netcdf4
    - numba
    - geocat-datafiles
    - xskillscore
  imports:
    - geocat
    - geocat.comp
  commands:
    - pip check
    - pytest test
    - conda info
    - conda list
  source_files:
    - test

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-comp is a Python package containing a subset of NCL (NCAR Command Language) computational routines.
  dev_url: https://github.com/NCAR/{{ name }}
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - hCraker # H. Craker https://github.com/hCraker
    - marodrig # M. Rodriguez https://github.com/marodrig
    - michaelavs # M. Sizemore https://github.com/michaelavs
    - pilotchute # A. Kootz https://github.com/pilotchute
