{% set python_min = "3.10" %}
{% set name = "geocat-comp" %}
{% set version = "2025.07.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: a703e058ec1d369b48f0750f86a902543bbef497147ff2f9f97126323c288cce
  # git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: main # For building from main branch for debugging purposes
  # git_url: https://github.com/NCAR/{{ name }}.git

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - cf_xarray >=0.3.1
    - cftime
    - dask-core
    - distributed
    - eofs
    - metpy
    - numba
    - numpy
    - packaging
    - scipy
    - xarray
    - xskillscore >=0.0.17

test:
  requires:
    - python {{ python_min }}
  imports:
    - geocat
    - geocat.comp
  commands:
    # print package version
    - python -c "import geocat.comp; print(geocat.comp.__version__)"

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-comp is a Python package containing a subset of NCL (NCAR Command Language) computational routines.
  dev_url: https://github.com/NCAR/{{ name }}
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyschneck # C. Schneck https://github.com/cyschneck
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - jukent # J. Kent https://github.com/jukent/
    - kafitzgerald # K. FitzGerald https://github.com/kafitzgerald
