{% set name = "geocat-comp" %}
{% set version = "2024.01.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: 7ab59c4e33661509055e335b0533a8c6b2a6819527f5d0b3e179fa59ab342836
  # git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: main # For building from main branch for debugging purposes
  # git_url: https://github.com/NCAR/{{ name }}.git

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python >=3.9, <3.12
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9, <3.12
    - cf_xarray >=0.3.1
    - cftime
    - dask
    - distributed
    - eofs
    - metpy
    - netcdf4
    - numba
    - numpy
    - pint
    - scipy
    - xarray
    - xskillscore

test:
  requires:
    - pytest
  imports:
    - geocat
    - geocat.comp
  commands:
    # print package version
    - python -c "import geocat.comp; print(geocat.comp.__version__)"

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-comp is a Python package containing a subset of NCL (NCAR Command Language) computational routines.
  dev_url: https://github.com/NCAR/{{ name }}
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyschneck # C. Schneck https://github.com/cyschneck
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - jukent # J. Kent https://github.com/jukent/
    - kafitzgerald # K. FitzGerald https://github.com/kafitzgerald
